[package]
name = "aoc-2k24"
version = "0.1.0"
edition = "2021"
author = "Shashank Verma (shank03)"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
regex = "1.11.1"
reqwest = { version = "0.12.9", features = ["blocking"] }
